# Generated by Django 4.2.11 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephonenumbercatalogue',
            name='odt_file',
        ),
        migrations.AddField(
            model_name='telephonenumbercatalogue',
            name='ods_file',
            field=models.FileField(null=True, upload_to='ods/', verbose_name='ods file'),
        ),
    ]
